name: Build Executables with PyInstaller

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-windows:
    runs-on: windows-latest # Use a Windows runner for Windows executables
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your desired Python version

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r app/requirements.txt # If you have a requirements.txt file

      - name: Build executable
        run: |
          cd app
          python3 build_executable.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: app/dist/run # Adjust path to your executable

  build-linux:
    runs-on: ubuntu-latest # Use a Linux runner for Linux executables
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r app/requirements.txt

      - name: Build executable
        run: |
          cd app
          python3 build_executable.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: app/dist/run # Adjust path to your executable

  build-macos:
    runs-on: macos-latest # Use a macOS runner for macOS executables
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r app/requirements.txt

      - name: Build executable
        run: |
          cd app
          python3 build_executable.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: app/dist/run # Adjust path to your executable
